5350 Thesis in Economics

Andres Cruz 25199 & Klara Holmer 25037 

Code for Grundskola and Gymnasieskola

In [23]:
# Importing Libraries
import numpy as np 
import pandas as pd 
import glob
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
# Step 1 - Importing ExcelFiles and Concatenating DataFrames

# --- Gymnasieskola  Årskurs 1 or Upper Secondary School Year 10 --- 

# Defining the full path to the Excel file in the new folder
pathname = '/Users/andrescruz/Documents/Handelshögskolan/MSc Economic/Semester 4/5350 Thesis in Economics/Processed Data/gymnasieskola_ämnen.xlsx'

# Read all sheets at once into a dictionary
sheets = ['English', 'Mathematics', 'Swedish']
gymnasieskola_data = pd.read_excel(pathname, sheet_name=sheets)

# Unpack the dictionary into separate variables if needed
gymnasieskola_data_english = gymnasieskola_data['English']
gymnasieskola_data_mathematics = gymnasieskola_data['Mathematics']
gymnasieskola_data_swedish = gymnasieskola_data['Swedish']

# --- Lower Secondary School Year 9 --- 

# Defining the full path to the Excel file in the new folder
pathname = '/Users/andrescruz/Documents/Handelshögskolan/MSc Economic/Semester 4/5350 Thesis in Economics/Processed Data/grundskola_ämnen.xlsx'

# Read all sheets at once into a dictionary
sheets = ['English', 'Mathematics', 'Swedish']
grundskola_data = pd.read_excel(pathname, sheet_name=sheets)

# Unpack the dictionary into separate variables if needed
grundskola_data_english = grundskola_data['English']
grundskola_data_mathematics = grundskola_data['Mathematics']
grundskola_data_swedish_data = grundskola_data['Swedish']

# --- Concatenating --- 

# Engelska
school_data_english = pd.concat([gymnasieskola_data_english, grundskola_data_english], ignore_index=True)

# Matematik
school_data_mathematics = pd.concat([gymnasieskola_data_mathematics, grundskola_data_mathematics], ignore_index=True)

# Svenska
school_data_swedish = pd.concat([gymnasieskola_data_swedish, grundskola_data_swedish_data], ignore_index=True)

# List of DataFrames
dataframes = [school_data_english, school_data_mathematics, school_data_swedish]

gymnasieskola_data_english

,school_ID,school_municipality,municipality_ID,type_of_ownership,academic_year,educational_stage,school_size,total_school_students,graduating_students,graduates_average_grade_points,...,share_foreign_background,share_postsecondary_parents,total_fulltime_teachers,total_fulltime_certified_teachers,share_fulltime_certified_teachers,total_active_teachers,total_active_certified_teachers,share_active_certified_teachers,share_students_A_E_eng,share_students_F_eng
0,74776778,Alingsås,1489,Kommunal,2014/15,gymnasieskola,100-199,135.0,44.0,14.7,...,19.0,46.0,7.7,6.1,78.8,20.0,15.0,75.0,97.7,2.3
1,18345915,Alingsås,1489,Kommunal,2014/15,gymnasieskola,200-299,211.0,41.0,15.2,...,16.0,67.0,14.2,13.8,97.2,29.0,27.0,93.1,100.0,0.0
2,68229719,Alingsås,1489,Kommunal,2014/15,gymnasieskola,100-199,155.0,45.0,14.8,...,14.0,53.0,13.1,12.6,95.9,23.0,21.0,91.3,100.0,0.0
3,61004230,Alingsås,1489,Kommunal,2014/15,gymnasieskola,50-99,94.0,44.0,16.5,...,NaN,62.0,8.8,6.0,68.3,16.0,12.0,75.0,100.0,0.0
4,71262305,Arboga,1984,Kommunal,2014/15,gymnasieskola,100-199,183.0,63.0,15.5,...,13.0,68.0,23.2,15.9,68.4,27.0,19.0,70.4,100.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,47559319,Östersund,2380,Enskild,2021/22,gymnasieskola,50-99,83.0,34.0,12.8,...,40.0,53.0,8.1,5.9,73.7,11.0,8.0,72.7,100.0,0.0
6202,20752831,Österåker,117,Kommunal,2021/22,gymnasieskola,500-599,564.0,172.0,13.5,...,13.0,69.0,21.0,14.0,66.7,35.0,24.0,68.6,98.8,1.2
6203,51023367,Östhammar,382,Kommunal,2021/22,gymnasieskola,100-199,166.0,55.0,14.6,...,14.0,54.0,17.6,15.9,90.5,30.0,25.0,83.3,100.0,0.0
6204,34739511,Östhammar,382,Enskild,2021/22,gymnasieskola,50-99,59.0,23.0,14.5,...,NaN,68.0,9.5,7.0,73.6,12.0,8.0,66.7,100.0,0.0
6205,52690153,Övertorneå,2518,Kommunal,2021/22,gymnasieskola,50-99,57.0,18.0,16.0,...,23.0,63.0,9.1,7.5,82.2,16.0,13.0,81.3,100.0,0.0

In [25]:
# Step 2 -  Adding County ID 

# Defining the full path to the Excel file in the new folder
pathname = '/Users/andrescruz/Documents/Handelshögskolan/MSc Economic/Semester 4/5350 Thesis in Economics/Raw Data/Kommun Data/georef-sweden-kommun.xlsx'

# Read all sheets at once into a dictionary
kommun_data = pd.read_excel(pathname, sheet_name=0)

# List of new names 
new_names = [
    'geo_point',            # Column 1 Geo Point
    'geo_shape',            # Column 2 Geo Shape
    'year',                 # Column 3 Year
    'county_ID',            # Column 4 Län code
    'school_county',        # Column 5 Län name
    'municipality_ID',      # Column 6 Kommun code
    'school_municipality',  # Column 7 Kommun name
    'area_code',            # Column 8 ISO 3166-3 Area code
    'type',                 # Column 9 Type
    ]

# List of new names 
columns_to_drop = [
    'geo_point',            # Column 1 Geo Point
    'geo_shape',            # Column 2 Geo Shape
    'year',                 # Column 3 Year
    'area_code',            # Column 8 ISO 3166-3 Area code
    'type',                 # Column 9 Type
    ]

# Applying the new names 
kommun_data.columns = new_names

# Drop the specified columns
kommun_data.drop(columns=columns_to_drop, axis=1, inplace=True)

# Define the join keys
join_keys = ['school_municipality', 'municipality_ID']

# Apply merging and store the results back in the list
dataframes = [pd.merge(df, kommun_data, on=join_keys, how='left') for df in dataframes]

# Unpacking the list 
school_data_english, school_data_mathematics, school_data_swedish = dataframes

school_data_english

,school_ID,school_municipality,municipality_ID,type_of_ownership,academic_year,educational_stage,school_size,total_school_students,graduating_students,graduates_average_grade_points,...,total_fulltime_teachers,total_fulltime_certified_teachers,share_fulltime_certified_teachers,total_active_teachers,total_active_certified_teachers,share_active_certified_teachers,share_students_A_E_eng,share_students_F_eng,county_ID,school_county
0,74776778,Alingsås,1489,Kommunal,2014/15,gymnasieskola,100-199,135.0,44.0,14.7,...,7.7,6.1,78.8,20.0,15.0,75.0,97.7,2.3,14,Västra Götalands län
1,18345915,Alingsås,1489,Kommunal,2014/15,gymnasieskola,200-299,211.0,41.0,15.2,...,14.2,13.8,97.2,29.0,27.0,93.1,100.0,0.0,14,Västra Götalands län
2,68229719,Alingsås,1489,Kommunal,2014/15,gymnasieskola,100-199,155.0,45.0,14.8,...,13.1,12.6,95.9,23.0,21.0,91.3,100.0,0.0,14,Västra Götalands län
3,61004230,Alingsås,1489,Kommunal,2014/15,gymnasieskola,50-99,94.0,44.0,16.5,...,8.8,6.0,68.3,16.0,12.0,75.0,100.0,0.0,14,Västra Götalands län
4,71262305,Arboga,1984,Kommunal,2014/15,gymnasieskola,100-199,183.0,63.0,15.5,...,23.2,15.9,68.4,27.0,19.0,70.4,100.0,0.0,19,Västmanlands län
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19472,50308658,Överkalix,2513,Kommunal,2021/22,grundskola,100-199,118.0,16.0,11.4,...,14.8,7.9,53.0,19.0,11.0,57.9,75.0,25.0,25,Norrbottens län
19473,13342436,Överkalix,2513,Enskild,2021/22,grundskola,50-99,54.0,NaN,NaN,...,6.1,1.7,27.6,7.0,5.0,71.4,NaN,NaN,25,Norrbottens län
19474,46252858,Övertorneå,2518,Enskild,2021/22,grundskola,50-99,62.0,11.0,15.2,...,6.9,2.3,33.2,10.0,4.0,40.0,100.0,0.0,25,Norrbottens län
19475,90707437,Övertorneå,2518,Kommunal,2021/22,grundskola,50-99,72.0,12.0,13.5,...,7.9,3.6,45.4,16.0,10.0,62.5,100.0,0.0,25,Norrbottens län
19476,18991431,Övertorneå,2518,Kommunal,2021/22,grundskola,100-199,147.0,25.0,12.1,...,15.6,12.0,76.9,24.0,20.0,83.3,92.0,8.0,25,Norrbottens län

In [26]:
# Step 3 -  Imputing and dropping columns

# List of DataFrames
dataframes = [school_data_english, school_data_mathematics, school_data_swedish]

# Columns to fill via group-wise backward fill
columns_to_bfill = ['school_size', 'total_school_students', 'graduating_students']

# Define bins and labels for school size categorization
bins = [0, 49, 99, 199, 299, 399, 499, 599, 699, 799, 899, np.inf]
labels = ["1-49", "50-99", "100-199", "200-299", "300-399", "400-499", 
          "500-599", "600-699", "700-799", "800-899", "900-"]

# Define a list of columns to drop
columns_to_drop = [
    'total_fulltime_teachers',                                           
    'share_fulltime_certified_teachers',                                    
    'total_active_teachers',                                            
    'total_active_certified_teachers',                                    
    ]

# For Loop 
for df in dataframes:
    # Step 1: Group-wise backward fill for specified columns
    df[columns_to_bfill] = df.groupby('school_ID')[columns_to_bfill].bfill()

    # Step 2: Categorize total_school_students into school_size
    df['school_size'] = pd.cut(
        df['total_school_students'].astype(float),  # Ensure numeric type
        bins=bins,
        labels=labels,
        right=True
    )

    # Dropping columns which will not be used
    df.drop(columns=columns_to_drop, axis=1, inplace=True)

In [27]:
# Step 4 - Exporting 

# Defining the full path where the Excel file will be saved
pathname = '/Users/andrescruz/Documents/Handelshögskolan/MSc Economic/Semester 4/5350 Thesis in Economics/Processed Data/school_data_ämnen.xlsx'

# Exporting all the tables created into one Excel File 
with pd.ExcelWriter(pathname) as writer:
    school_data_english.to_excel(writer, sheet_name = 'English', index=False)
    school_data_mathematics.to_excel(writer, sheet_name = 'Mathematics', index=False)
    school_data_swedish.to_excel(writer, sheet_name = 'Swedish', index=False)